---
version: '3'
services:
  'verify':
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: service_rddl_verify
    ports:
      - '8000:8000'
    tty: true
    volumes:
      - ./rddl_verify:/rddl_verify
    command: sh -c "uvicorn rddl_verify.main:app --host 0.0.0.0 --port 8000 --timeout-keep-alive 240 --reload"
